server:
  port: 8888

eureka:
  instance:
    hostname: eureka-server1
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone:  http://localhost:8889/eureka/
  #\u662F\u5426\u5F00\u542F\u5B89\u5168\u4FDD\u62A4\uFF0C\u9ED8\u8BA4\u662F\u5F00\u542F\u7684\uFF0C\u5982\u679C\u9ED8\u8BA4\u5F00\u542F\uFF0C\u6CE8\u518C\u4E2D\u5FC3\u7684\u670D\u52A1\u5217\u8868\u5C31\u7B97\u6709\u4E9B\u670D\u52A1\u65AD\u5F00\u4E86\uFF0C\u4E5F\u4F1A\u7EE7\u7EED\u4FDD\u5B58
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-service
